# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: Maven@3
  displayName: Build & Test
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install package'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'artifacts'
    publishLocation: 'pipeline'
    fileSharePath: 'artifacts'

- task: MS-EASBuild.BuildNotification.task-BuildNotification.BuildNotification@1
  displayName: 'Email Build Notification'
  inputs:
    MailFrom: 'email@gmail.com'
    MailTo: 'email@gmail.com
    SmtpServer: smtp.gmail.com
    BannerHeader: 'Build Results'
    MailPwd: $(mailapppasswd)
    PAT: $(AzurePAT)

